/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        primary: {
          DEFAULT: 'var(--color-primary)',
          dark: 'var(--color-primary-dark)',
          light: 'var(--color-primary-light)',
          glow: 'var(--color-primary-glow)',
        },
        accent: {
          cyan: '#48D7E8',
          pink: '#D95CFF',
          purple: '#6C4FF6',
        },
        app: {
          bg: 'var(--color-bg)',
          surface: 'var(--color-surface)',
          'surface-secondary': 'var(--color-surface-secondary)',
          text: 'var(--color-text-primary)',
          'text-secondary': 'var(--color-text-secondary)',
          'text-muted': 'var(--color-text-muted)',
          border: 'var(--color-border)',
          'border-strong': 'var(--color-border-strong)',
          success: 'var(--color-success)',
          warning: 'var(--color-warning)',
          error: 'var(--color-error)',
        },
        // Backward compatibility mappings
        warm: {
          bg: 'var(--color-bg)',
          card: 'var(--color-surface)',
          'card-subtle': 'var(--color-surface-secondary)',
          border: 'var(--color-border)',
          'border-strong': 'var(--color-border-strong)',
          text: 'var(--color-text-primary)',
          muted: 'var(--color-text-secondary)',
          faint: 'var(--color-text-muted)',
          accent: 'var(--color-primary)',
          'accent-hover': 'var(--color-primary-dark)',
          'accent-light': 'var(--color-primary-light)',
          sage: '#48B884',
          'sage-light': '#EBFBF3',
          ochre: '#F4B740',
          'ochre-light': '#FEF8EB',
          indigo: '#6C4FF6',
          'indigo-light': '#F1EEFF',
          rose: '#E65C6A',
          'rose-light': '#FDF0F1',
        },
      },
      fontFamily: {
        sans: ['"Plus Jakarta Sans"', 'Inter', 'Manrope', '-apple-system', 'BlinkMacSystemFont', 'sans-serif'],
        mono: ['"JetBrains Mono"', 'monospace'],
        serif: ['Lora', 'Georgia', 'serif'],
      },
      boxShadow: {
        subtle: '0 1px 3px 0 rgba(40, 35, 80, 0.03), 0 1px 2px -1px rgba(40, 35, 80, 0.03)',
        soft: '0 4px 20px -2px rgba(40, 35, 80, 0.05), 0 2px 6px -1px rgba(40, 35, 80, 0.02)',
        workspace: '0 10px 40px rgba(40, 35, 80, 0.05)',
        elevated: '0 16px 36px -4px rgba(40, 35, 80, 0.08), 0 4px 12px -2px rgba(40, 35, 80, 0.04)',
        glow: '0 0 24px -4px var(--color-primary-glow)',
      },
      borderRadius: {
        sm: '10px',
        md: '12px',
        lg: '14px',
        xl: '16px',
        '2xl': '18px',
        card: '18px',
        '3xl': '24px',
        '4xl': '28px',
        workspace: '28px',
      },
      animation: {
        'pulse-subtle': 'pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'wave-bar': 'wave 1.2s ease-in-out infinite alternate',
        'fade-in': 'fadeIn 0.25s ease-out forwards',
        'slide-up': 'slideUp 0.3s cubic-bezier(0.16, 1, 0.3, 1) forwards',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideUp: {
          '0%': { opacity: '0', transform: 'translateY(8px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        wave: {
          '0%': { transform: 'scaleY(0.2)' },
          '100%': { transform: 'scaleY(1)' },
        },
      },
    },
  },
  plugins: [],
};
