import React from 'react';
import {
  Sparkles,
  Heart,
  TrendingUp,
  Compass,
  ArrowRight,
  BookMarked,
  Quote,
} from 'lucide-react';
import type { JournalEntry } from '../types';
import { storageService } from '../services/storage/storageService';
import { formatDuration } from '../services/media/mediaUtils';
import { getMoodDetails } from '../components/common/MoodSelector';

interface InsightsPageProps {
  entries: JournalEntry[];
  onOpenEntry: (id: string) => void;
}

export const Insights: React.FC<InsightsPageProps> = ({
  entries,
  onOpenEntry,
}) => {
  const stats = storageService.getStats();

  const favoriteEntries = entries.filter((e) => e.isFavorite);
  const topMoodInfo = getMoodDetails(stats.topMood || undefined);

  return (
    <div className="space-y-10 max-w-4xl mx-auto animate-fade-in">
      {/* Header */}
      <section className="space-y-2">
        <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-warm-card border border-warm-border text-warm-muted text-xs font-semibold">
          <Compass className="w-3.5 h-3.5 text-warm-accent" />
          <span>Long-Term Reflection</span>
        </div>
        <h1 className="font-serif text-3xl sm:text-4xl lg:text-5xl font-medium tracking-tight text-warm-text">
          Your Journey
        </h1>
        <p className="text-sm sm:text-base text-warm-muted max-w-xl leading-relaxed">
          Quiet observations, recurring patterns, and moments of pride gathered across your memories.
        </p>
      </section>

      {/* 1. Journey Summary Metrics */}
      <section className="grid grid-cols-2 sm:grid-cols-4 gap-3 sm:gap-4">
        <div className="bg-warm-card border border-warm-border rounded-3xl p-5 shadow-subtle">
          <span className="text-xs text-warm-muted block mb-1">Total Memories</span>
          <p className="font-serif text-3xl sm:text-4xl font-medium text-warm-text">
            {stats.totalEntries}
          </p>
          <span className="text-[11px] text-warm-faint mt-1 block">
            {stats.entriesThisMonth} this month
          </span>
        </div>

        <div className="bg-warm-card border border-warm-border rounded-3xl p-5 shadow-subtle">
          <span className="text-xs text-warm-muted block mb-1">Words Written</span>
          <p className="font-serif text-3xl sm:text-4xl font-medium text-warm-text">
            {stats.wordCount.toLocaleString()}
          </p>
          <span className="text-[11px] text-warm-faint mt-1 block">
            Deep reflections
          </span>
        </div>

        <div className="bg-warm-card border border-warm-border rounded-3xl p-5 shadow-subtle">
          <span className="text-xs text-warm-muted block mb-1">Spoken Time</span>
          <p className="font-serif text-3xl sm:text-4xl font-medium text-warm-text">
            {formatDuration(stats.audioDurationSeconds + stats.videoDurationSeconds)}
          </p>
          <span className="text-[11px] text-warm-faint mt-1 block">
            Audio & video logs
          </span>
        </div>

        <div className="bg-warm-card border border-warm-border rounded-3xl p-5 shadow-subtle">
          <span className="text-xs text-warm-muted block mb-1">Primary State</span>
          <div className="flex items-center gap-2 mt-1">
            <span className="text-2xl">{topMoodInfo?.emoji || '🌱'}</span>
            <span className="font-serif text-xl sm:text-2xl font-medium text-warm-text capitalize">
              {topMoodInfo?.label || 'Calm'}
            </span>
          </div>
          <span className="text-[11px] text-warm-faint mt-1 block">
            Most frequent
          </span>
        </div>
      </section>

      {/* 2. Detected Emotional & Behavioral Patterns */}
      <section className="space-y-4">
        <div className="flex items-center justify-between">
          <div>
            <h2 className="font-serif text-xl sm:text-2xl font-medium text-warm-text flex items-center gap-2">
              <Sparkles className="w-5 h-5 text-warm-accent" />
              <span>Observed Patterns</span>
            </h2>
            <p className="text-xs text-warm-muted mt-0.5">
              Generated by analyzing recurring topics and emotional shifts in your entries
            </p>
          </div>
          <span className="text-[10px] uppercase font-bold tracking-wider text-warm-faint bg-warm-card-subtle px-2.5 py-1 rounded-full border border-warm-border">
            AI Synthesis
          </span>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          <div className="bg-warm-card border border-warm-border rounded-3xl p-6 shadow-subtle space-y-3">
            <div className="flex items-center gap-2 text-warm-accent text-xs font-semibold">
              <TrendingUp className="w-4 h-4" />
              <span>Career & Performance Cycle</span>
            </div>
            <p className="text-sm text-warm-text leading-relaxed font-serif">
              "You've mentioned high-stakes presentations and deadlines several times. You often describe acute physical nervousness beforehand, which consistently dissolves into relief and competence once you engage."
            </p>
            <div className="pt-2 border-t border-warm-border/60 text-xs text-warm-muted">
              Suggested insight: Trust your preparation instincts; early anxiety has not predicted performance.
            </div>
          </div>

          <div className="bg-warm-card border border-warm-border rounded-3xl p-6 shadow-subtle space-y-3">
            <div className="flex items-center gap-2 text-emerald-600 dark:text-emerald-400 text-xs font-semibold">
              <TrendingUp className="w-4 h-4" />
              <span>Restoration & Sensory Grounding</span>
            </div>
            <p className="text-sm text-warm-text leading-relaxed font-serif">
              "When creative fatigue arrives, physical sensory rituals—cooking sourdough pasta, walking without headphones, shooting 35mm film—consistently restore your mental clarity."
            </p>
            <div className="pt-2 border-t border-warm-border/60 text-xs text-warm-muted">
              Suggested insight: Tactile hobbies serve as your most effective defense against cognitive overstimulation.
            </div>
          </div>
        </div>
      </section>

      {/* 3. Recurring Themes */}
      <section className="bg-warm-card border border-warm-border rounded-3xl p-6 sm:p-8 shadow-subtle space-y-6">
        <div>
          <h2 className="font-serif text-xl sm:text-2xl font-medium text-warm-text">
            What you've been talking about
          </h2>
          <p className="text-xs text-warm-muted mt-1">
            Top themes recurring in your entries and AI reflections
          </p>
        </div>

        <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
          {stats.topThemes.map(({ theme, count }) => (
            <div
              key={theme}
              className="p-4 rounded-2xl bg-warm-card-subtle/80 border border-warm-border/80 flex flex-col justify-between"
            >
              <span className="text-xs font-medium text-warm-text leading-snug">
                {theme}
              </span>
              <div className="flex items-center justify-between mt-3 text-[11px] text-warm-muted">
                <span>{count} mentions</span>
                <span className="font-mono text-warm-accent font-semibold">
                  {Math.round((count / Math.max(1, stats.totalEntries)) * 100)}%
                </span>
              </div>
            </div>
          ))}
        </div>
      </section>

      {/* 4. Moments You've Been Proud Of (Favorites / High-Mood Memories) */}
      <section className="space-y-4">
        <div>
          <h2 className="font-serif text-xl sm:text-2xl font-medium text-warm-text flex items-center gap-2">
            <Heart className="w-5 h-5 text-rose-500 fill-rose-500" />
            <span>Memories you cherish</span>
          </h2>
          <p className="text-xs text-warm-muted mt-0.5">
            Starred reflections and milestones worth revisiting
          </p>
        </div>

        {favoriteEntries.length === 0 ? (
          <div className="bg-warm-card border border-warm-border rounded-3xl p-8 text-center space-y-2">
            <BookMarked className="w-6 h-6 text-warm-muted mx-auto" />
            <h3 className="text-sm font-semibold text-warm-text">
              No favorited memories yet
            </h3>
            <p className="text-xs text-warm-muted max-w-sm mx-auto">
              Click the heart icon on any journal entry to pin your most meaningful memories here.
            </p>
          </div>
        ) : (
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            {favoriteEntries.map((entry) => (
              <div
                key={entry.id}
                onClick={() => onOpenEntry(entry.id)}
                className="bg-warm-card border border-warm-border rounded-3xl p-6 shadow-subtle hover:border-warm-border-strong hover:shadow-soft transition-all cursor-pointer flex flex-col justify-between"
              >
                <div>
                  <div className="flex items-center justify-between text-xs text-warm-muted mb-2">
                    <span className="capitalize">{entry.type} Entry</span>
                    <Heart className="w-3.5 h-3.5 text-rose-500 fill-rose-500" />
                  </div>
                  <h3 className="font-serif text-xl font-medium text-warm-text mb-2">
                    {entry.title}
                  </h3>
                  <p className="text-xs text-warm-muted line-clamp-3 leading-relaxed">
                    {entry.text || entry.transcript || 'Reflected memory.'}
                  </p>
                </div>

                <div className="flex items-center justify-between pt-4 mt-4 border-t border-warm-border/60 text-xs text-warm-faint">
                  <span>{new Date(entry.createdAt).toLocaleDateString()}</span>
                  <span className="text-warm-accent font-medium flex items-center gap-1">
                    Revisit <ArrowRight className="w-3 h-3" />
                  </span>
                </div>
              </div>
            ))}
          </div>
        )}
      </section>

      {/* 5. A Note on Privacy & AI Synthesis */}
      <section className="p-6 rounded-3xl bg-warm-card-subtle border border-warm-border text-xs text-warm-muted space-y-2">
        <div className="flex items-center gap-2 font-semibold text-warm-text">
          <Quote className="w-4 h-4 text-warm-accent" />
          <span>Factual Journal Data vs. Generated Insights</span>
        </div>
        <p className="leading-relaxed">
          Your journal text, transcripts, and media files are stored locally on your device. The insights above are generated observations meant to support personal contemplation, never factual judgments or clinical diagnoses.
        </p>
      </section>
    </div>
  );
};
